// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqoduwkocpqmrvpuklkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxb2R1d2tvY3BxbXJ2cHVrbGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDEzMTMsImV4cCI6MjA2NTgxNzMxM30.kSXUevzgxr_U7_FVHiGYl3QMXuIZhGeEYmK9lDQnL1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);